pull_request_rules:
  - name: merge dependabot pull request
    conditions:
      - author=dependabot[bot]
      - -merged
      - -closed
      - -locked
      - -conflict
      - "check-success=docker"
      - "check-success=ci"
    actions:
      merge:
        method: merge