logFilters:
  - pattern: fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The * architecture is incompatible with this module, link skipped.
    level: discard

nodeLinker: node-modules

packageExtensions:
  vue-loader@15.9.8:
    peerDependenciesMeta:
      "@vue/compiler-sfc":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
